version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - docker build -t git.systementor.se/david.lindgren.kamali/gc .
      - docker login -u david.lindgren.kamali -p yacloud1 https://git.systementor.se
      - docker push git.systementor.se/david.lindgren.kamali/gc
